clear;

files = dir('detector*.mat');

for i = 1:length(files)
    disp(sprintf('File %s...', files(i).name));
    load(files(i).name);
    
    mmmout_xmin = net.outputs{2}.processSettings{1}.xmin;
    mmmout_ymin = net.outputs{2}.processSettings{1}.ymin;
    mmmout_gain = net.outputs{2}.processSettings{1}.gain;    
    
    save(files(i).name, ...
        'net', 'train_record', ...
        'samplerate', 'fft_size', 'win_size', 'fft_time_shift', 'fft_time_shift_seconds', 'freq_range_ds', ...
        'time_window_steps', 'trigger_thresholds', 'freq_range', ...
        'layer0', 'layer1', 'bias0', 'bias1', ...
        'mmmout_xmin', 'mmmout_ymin', 'mmmout_gain', 'mapstd_xmean', 'mapstd_xstd', ...
        'shotgun_sigma', ...
        'ntrain',  'scaling', '-v7');
end
